---
include:
  - board: sofle_right
    shield: nice_view_custom
  - board: sofle_left
    shield: nice_view
    artifact-name: sofle_left_nostudio
  - board: sofle_left
    shield: nice_view
    snippet: zmk-usb-logging
    artifact-name: sofle_left_logging
  - board: sofle_left
    shield: settings_reset